### ISSUE TITLE
Houses too frequent.

### ISSUE THREAD

**Issue by Rexile** [TheFloydman/More-Mystcraft#1]
I just can't find the mod in the config option to change the frequency of the house spawning. Every 10~ chunks a new one is there...

**Comment by TheFloydman** [comment]
Yes, I plan on reducing the frequency by a factor of 10. A config option sounds like a good idea though.

**Comment by Rexile** [comment]
Awesome! Great work though!

**Comment by TheFloydman** [comment]
Version 0.1.2 has addressed both of these issues. Thanks for the suggestions! (https://minecraft.curseforge.com/projects/more-mystcraft/files/2618935)
