### ISSUE TITLE
Tinted Sun Celestial generating extra Tilt modifiers

### ISSUE THREAD

**Issue by Atrius97** [TheFloydman/More-Mystcraft#12]
**What version of *More Mystcraft* are you using?**
0.5.2 (Dev Build, provided while testing bugfix for Tinted Sun rendering)

**What version of *Mystcraft* are you using?**
0.13.7.02

**What version of *Forge* are you using?**
14.23.5.2811

**What version of *Minecraft* are you using?**
1.12.2

**What modpack and modpack version are you using, if any?**
Myst25-1.12-1.2.5, bug also occurs in clean environment with only More-Mystcraft&Mystcraft.

**Describe the bug**
When generating a Tinted Sun in an age, the grammar is unsatisfied with using a single Tilt Modifier.
This typically results in additional Tilt modifiers being added despite being fully defined otherwise, and generates a Tinted Sun celestial with said additional modifiers.

**Screenshots**
![2019-02-14_21 10 17](https://user-images.githubusercontent.com/39707481/52869528-121c0580-3103-11e9-989d-ed136fdd439c.png)
The Tinted Sun generated in this instance was intended to be "Zero Length, Nadir, North, West, No Tilt"
The final result seen in the Age and Age Data was "Zero Length, Nadir, North, West, Half Tilt, No Tilt"

**Comment by TheFloydman** [comment]
This has been fixed and will appear in the next release.
