### ISSUE TITLE
[0.5.3] Cloud Height Modifiers Non-Functional

### ISSUE THREAD

**Issue by Atrius97** [TheFloydman/More-Mystcraft#14]
**What version of *More Mystcraft* are you using?**
0.5.3

**What version of *Mystcraft* are you using?**
0.13.7.02

**What version of *Forge* are you using?**
14.23.5.2820

**What version of *Minecraft* are you using?**
1.12.2

**What modpack and modpack version are you using, if any?**
Garternay 1.1.1 (Optifine Excluded)
However, this does occur in an a clean environment with only Mystcraft + More Mystcraft installed.

**Does the bug occur server-side, client-side, or both?**
Both

**Describe the bug**
The "Double/Full/Half/Zero Cloud Height" modifier pages do not seem to affect any ages generated using them. The clouds render at y-level 127, (or lower in the case of Skylands Ages) regardless of the modifier used.

**Comment by TheFloydman** [comment]
Thanks for pointing this out. It has been fixed and cloud height symbols will be fully functional in the next release.
