### ISSUE TITLE
Crash with Latest Mystcraft Version

### ISSUE THREAD

**Issue by Akaruz64** [TheFloydman/More-Mystcraft#15]
**What version of *More Mystcraft* are you using?**
0.5.4

**What version of *Mystcraft* are you using?**
0.13.7.03

**What version of *Forge* are you using?**
14.23.5.2836

**What version of *Minecraft* are you using?**
1.12.2

**What modpack and modpack version are you using, if any?**
None

**Does the bug occur server-side, client-side, or both?**
Client-side

**Paste a link to your log or crash report here. Use a service like pastebin. No images, please.**
https://pastebin.com/E3xJc3ce

**Describe the bug**
Crash with the latest Mystcraft version,

**To Reproduce**
Install both Mystcraft and more mystcraft

**Expected behavior**
Game to load?

**Additional context**
Temp Solution - Rollback to Mystcraft 7.02

**Comment by TheFloydman** [comment]
![Untitled](https://user-images.githubusercontent.com/22880199/56165901-045ef100-5f89-11e9-8813-c1c338f6baf2.png)

Mystcraft added some generation changes with the newest release, and More Mystcraft will be incompatible until those changes are reconciled.

**Comment by TheFloydman** [comment]
There was a method in Mystcraft that has become unobfuscated. Things should work normally in the now-released next version unless something else is found.

https://minecraft.curseforge.com/projects/more-mystcraft/files/2699797
