### ISSUE TITLE
Tinted Sun does not respect length modifiers - adds a large amount of extra pages if used.

### ISSUE THREAD

**Issue by Kizzycocoa** [TheFloydman/More-Mystcraft#17]
**What version of *More Mystcraft* are you using?**
0.5.6

**What version of *Mystcraft* are you using?**
0.13.7.03

**What version of *Forge* are you using?**
14.23.5.2838

**What version of *Minecraft* are you using?**
1.12.2

**What modpack and modpack version are you using, if any?**
N/A (Custom, with AbyssalCraft)

**Does the bug occur server-side, client-side, or both?**
Server-side(both?)

**Paste a link to your log or crash report here. Use a service like pastebin. No images, please.**
https://discordapp.com/channels/223007335260487680/448149538549661706/594629617571332119

**Describe the bug**
Any attempt to make the sun zero-phase ends in failure. It also adds a variety of gradient and sunset pages without prompt.

**To Reproduce**
1) Make the following book:

Darkland Mountains, Single Biome, Stone Block, No Seas,
Standard World, East Direction, Zero Length, Zenith Phase,
Huge Size, No Tilt, Green Colour, Tinted Sun,
Dark Moon, Dark Stars, Normal Lighting, No Weather,
Natural Cloud Colour, Natural Fog Colour, Natural Foilage Colour, Natural Grass Colour,
Natural Sky Colour, Natural Water Colour, Lacking Large Features, Abandoned Studies,
Nether Brick Block, Obelisks

2) Observe the sun in-game

**Expected behavior**
The sun stays hung in the sky

**Actual behavior**
The sun moves in a standard day/night rotation.

**Comment by TheFloydman** [comment]
This was resolved on Discord. Tinted Suns accept both a Color page (for the sun) and a Sunset Color page. The Sunset Color page accepts Gradient pages, which accept Color and Length pages. Essentially, this means if you do not include a Gradient page (and at least one Color for it), Mystcraft gets confused about where your color page is meant to go. So to avoid this problem, always include at least a Color + Gradient combo to help the grammar better understand. Red Color is the default sunset color.
