### ISSUE TITLE
Disabling the traffic cone recipe and block in config will prevent you from crafting unlinked link books

### ISSUE THREAD

**Issue by boskoramen** [TheFloydman/More-Mystcraft#19]
No other mods were causing this issue. I limited my mod list to the latest versions of Mystcraft (0.13.7.03) and More Mystcraft (0.6.1). This bug even prevented me from using a custom shapeless recipe through Crafttweaker to circumvent not being able to make unlinked link books.

**Comment by TheFloydman** [comment]
Thank you for picking up on this. I discovered I was disabling recipes at the wrong time, which had some side effects. This will be fixed in the next release, which is planned for next Sunday during Mysterium.
