### ISSUE TITLE
Crash when entering new age, no crash report

### ISSUE THREAD

**Issue by Zsashas** [TheFloydman/More-Mystcraft#20]
https://github.com/XCompWiz/Mystcraft-Issues/issues/364

Wasn't sure whether this was a Mystcraft bug or a More Mystcraft bug.

**Comment by TheFloydman** [comment]
Given the lack of information, it's hard to tell, but I don't *think* it's a More Mystcraft problem. This mod just generates a blank linking book, so it's more likely a conflict between Mystcraft and another mod, especially since the first Abandoned Study book you used worked fine.

**Comment by Zsashas** [comment]
Maybe something to do with randomly picking one of the new symbols? If it happens again, I'll try to investigate further, although the world from this example has basically been orbitally nuked.
