### ISSUE TITLE
Crash on world load

### ISSUE THREAD

**Issue by BrisingrAerowing** [TheFloydman/More-Mystcraft#21]
**What version of *More Mystcraft* are you using?**
0.8.2

**What version of *Mystcraft* are you using?**
0.13.7.04

**What version of *Forge* are you using?**
14.23.5.2838

**What version of *Minecraft* are you using?**
1.12.2

**What modpack and modpack version are you using, if any?**
N/A

**Does the bug occur server-side, client-side, or both?**
Unknown (Singleplayer)

**Paste a link to your log or crash report here. Use a service like pastebin. No images, please.**
https://paste.dimdev.org/ayinajever.mccrash

**Describe the bug**
Crash on world load.

**To Reproduce**
1. Load a world
2. ...?
3. ~~Profit!~~ Crash!

**Expected behavior**
World loads normally.

**Screenshots**
N/A

**Additional context**

**Comment by BrisingrAerowing** [comment]
This may be an bug in AirHop. They recently did a fix for a desync on world load, and I think they may have messed it up a bit.

**Comment by TheFloydman** [comment]
Would you mind trying out this version for me? I can't tell if Air Hop has done anything wrong, but I'm hoping this will do the trick.
[moremystcraft-1.12.2-0.8.2.jar.zip](https://github.com/TheFloydman/More-Mystcraft/files/3522980/moremystcraft-1.12.2-0.8.2.jar.zip)

**Comment by BrisingrAerowing** [comment]
I’ll try when I get back to my computer.

**Comment by BrisingrAerowing** [comment]
Seems to work.

**Comment by TheFloydman** [comment]
Great, I will include the changes in the next release.
