### ISSUE TITLE
Crashing upon world creation

### ISSUE THREAD

**Issue by Xorbah** [TheFloydman/More-Mystcraft#22]
**What version of *More Mystcraft* are you using?**
0.8.3

**What version of *Mystcraft* are you using?**
0.13.7.02

**What version of *Forge* are you using?**
14.23.5.2838

**What version of *Minecraft* are you using?**
1.12.2

**Does the bug occur server-side, client-side, or both?**
Client Side.

**Crash Log**
https://paste.dimdev.org/ufefomedab.mccrash

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by TheFloydman** [comment]
The template exists to provide better context. Crash reports are often lacking. Can you please explain what you were doing when the error occured?

**Comment by Xorbah** [comment]
I wasn't doing anything. I was creating a world as the title of the report
stated. Midway into generating the world, VanillaFix told me that More
Mystcraft was the culprit albeit the crashlog not being very definitive as
to why.

**Comment by TheFloydman** [comment]
So this was from the single player menu and not when using a descriptive book?

**Comment by TheFloydman** [comment]
I _think_ this should be resolved in the next release.

**Comment by Xorbah** [comment]
No, it crashed during the process of a new world being generated.

**Comment by TheFloydman** [comment]
Repeating the same words back to me is not helpful. There are several ways to interpret "a new world was being generated", and I am trying to determine which way is the way you mean. It's made more confusing by the fact that each dimension can be called a "world". I was seeking more context is all. Whatever you were doing, it should be resolved in the next release.

**Comment by Xorbah** [comment]
Creating/generating a new world is a pretty straight forward statement,
there's not any other way of describing or interpreting it. You asked me
what it was that I was doing and I told you. I provided you with sufficient
information (version of Mystcraft, version of your mod, forge version,
crash log, action being done when issue took place).

I didn't say "Yeah I was going to the nether/the end and my game crashed"
so I'm not sure how you took this as anything other than me clicking the
"create new world" button. This wasn't hard to understand as I am speaking
completely fluently. Next time you want to try and be condescending at
least have valid and logical reasoning to do so.
