### ISSUE TITLE
Game crashes when nexus block is right clicked on

### ISSUE THREAD

**Issue by gassug3** [TheFloydman/More-Mystcraft#23]
**What version of *More Mystcraft* are you using?**
0.8.3

**What version of *Mystcraft* are you using?**
0.13.7.04

**What version of *Forge* are you using?**
14.23.5.2838

**What version of *Minecraft* are you using?**
1.12.2

**Does the bug occur server-side, client-side, or both?**
Client-side

**Paste a link to your log or crash report here. Use a service like pastebin. No images, please.**
https://pastebin.com/GFzGjZL1

**Describe the bug**
Nexus block crashes when right clicked on. Occured after a crash while handling descriptive books inside of the block.

**To Reproduce**
Bug seems inconsistent, and occurs when handling descriptive books (whether the same effect occurs for linking books or not is unknown to me). However, it seemed to have happened after a crash prior to this one. For the most part, the nexus works fine, although there is a chance of this bug occuring under unknown circumstances.

**Expected behavior**
I had expected to open the nexus block GUI.

**Comment by TheFloydman** [comment]
Added a null check that should resolve this particular issue.
