### ISSUE TITLE
Game crashes when cloth is right-clicked

### ISSUE THREAD

**Issue by gassug3** [TheFloydman/More-Mystcraft#24]
**What version of *More Mystcraft* are you using?**
0.8.3

**What version of *Mystcraft* are you using?**
0.13.7.04

**What version of *Forge* are you using?**
14.23.5.2838

**What version of *Minecraft* are you using?**
1.12.2

**Does the bug occur server-side, client-side, or both?**
Client-side

**Paste a link to your log or crash report here. Use a service like pastebin. No images, please.**
https://pastebin.com/TKngfFxG

**Describe the bug**
Game crashes when I had right-clicked with a cloth in hand. This was tested with two cloths of the three, and I'm uncertain whether it occurs with all three.

**To Reproduce**
1. Obtain a cloth
2. Right click with the cloth in hand
3. See error

**Expected behavior**
I'm not entirely sure what cloths are for, but it's more than safe to assume they wouldn't crash the game, especially when finished. I had expected to use the item instead.

**Comment by TheFloydman** [comment]
This was a problem with generating the correct blockstate for placement. It should only be placed on the horizontal sides of blocks, and it was running into an error there. Should be fixed in the next release.
