### ISSUE TITLE
World Load Crash

### ISSUE THREAD

**Issue by BrisingrAerowing** [TheFloydman/More-Mystcraft#26]
**What version of *More Mystcraft* are you using?**
0.8.5

**What version of *Mystcraft* are you using?**
0.13.7.04

**What version of *Forge* are you using?**
14.23.5.2847

**What version of *Minecraft* are you using?**
1.12.2

**What modpack and modpack version are you using, if any?**
N/A

**Does the bug occur server-side, client-side, or both?**
Server-side

**Paste a link to your log or crash report here. Use a service like pastebin. No images, please.**
https://paste.dimdev.org/bajizehuqe.mccrash

**Describe the bug**
Crash on world load / creation

**To Reproduce**
1. Load a world
2. ...
3. Crash

**Expected behavior**
World loads for play

**Screenshots**
N/A

**Additional context**
May possibly be a conflict with Hammer Core.

**Comment by BrisingrAerowing** [comment]
Hammer Core is not at fault here. I reentered the world and found a study made up of structure blocks. Recreating the world with the same seed leads to the same crash. I was in a desert-like biome. Looking at the code, it seems that the block map is null for some reason.

**Comment by TheFloydman** [comment]
Unfortunately, I cannot duplicate this issue in vanilla, so it's probably a mod incompatibility. Do you know if any of the mods you are using alter any vanilla blocks that might be used in the abandoned studies? Try this development version and see if it resolves the issue. If it doesn't, please send me the `latest.log` that generates after the crash, and provide a copy of your custom modpack if possible.

[moremystcraft-1.12.2-0.8.5.jar.zip](https://github.com/TheFloydman/More-Mystcraft/files/3666066/moremystcraft-1.12.2-0.8.5.jar.zip)

**Comment by BrisingrAerowing** [comment]
I’ll check when I get back to my computer.

**Comment by BrisingrAerowing** [comment]
One other thing: The study that crashes is literally right next to spawn.
Seed: -7655151774914657353

**Comment by BrisingrAerowing** [comment]
The test version hasn't crashed yet, but the study isn't even where it used to be.

**Comment by zane49er2** [comment]
I'm having the same crash in the newest release. Maybe the conflict is with underground biomes, which replaces cobblestone, or with BoP, which replaces woods.

**Comment by TheFloydman** [comment]
Fixed in most recent release.
