### ISSUE TITLE
Array index bounds exception when using Nexus Controller

### ISSUE THREAD

**Issue by imajunryou** [TheFloydman/More-Mystcraft#29]
**What version of *More Mystcraft* are you using?**
0.8.6

**What version of *Mystcraft* are you using?**
0.13.7.04

**What version of *Forge* are you using?**
14.23.5.2847

**What version of *Minecraft* are you using?**
1.12.2

**What modpack and modpack version are you using, if any?**
None

**Does the bug occur server-side, client-side, or both?**
Only attempted client-side

**Paste a link to your log or crash report here. Use a service like pastebin. No images, please.**
https://pastebin.com/AWc06kCq

**Describe the bug**
Interacting with the Nexus Controller when working with a single linking book can result in an array index bounds exception, crashing the game.  Reloading the game, accessing the Nexus Controller, and attempting to interact with the Linking Book causes another crash.

**To Reproduce**
1. Create a new world with at least Mystcraft and More Mystcraft installed, preferably in Creative
2. Add a Nexus Controller to your inventory
3. Place the Nexus Controller into the world
4. Add an Unlinked Linking Book to your inventory
5. With the Unlinked Linking Book in your hand, right-click the book.  This binds the book to a point in the Overworld, and replaces it with a Linking Book.
6. Right-click the Nexus Controller
7. Place the Linking Book in the bottom-left slot of the Nexus Controller interface.  This creates a clickable entry in the list at the top of the Nexus Controller interface, labeled "Overworld"
8. Click the "Overworld" entry in the list at the top of the Nexus Controller interface.  This places an image of the book's interior in the bottom center of the screen, and places the Linking Book in the bottom-right slot of the Nexus Controller's interface
9. Click in the empty space of the list at the top of the Nexus Controller interface, below the entry for "Overworld".  This causes the crash.

**Expected behavior**
I expected clicking into the empty portion of the list to have no effect.

**Screenshots**
Linking book inserted, list entry selected
![image](https://user-images.githubusercontent.com/4755440/80996162-9b008900-8dfc-11ea-9ec7-5735c8a5ca55.png)

List entry de-selected.  Interaction with the Nexus Controller beyond this point causes a crash.
![image](https://user-images.githubusercontent.com/4755440/80996229-b53a6700-8dfc-11ea-98cd-ce082c8b7d3c.png)

**Additional context**
No other context comes to mind.

**Comment by imajunryou** [comment]
A clarification:  The crash is caused specifically when attempting to pick up the Linking Book after it has been deselected from the Nexus Controller (see the second screenshot in the initial report above).

**Comment by TheFloydman** [comment]
Thank you for the clarification. It should just be a matter of making sure the linking book item disappears when the list item is deselected. I will be updating More Mystcraft soon to work with a soon-to-be-released library mod, so I will address this then. In the meantime, breaking the Nexus should release any books inside if you can't get it to open without a crash. Sorry for the inconvenience. I'll respond here when a fix is released.

**Comment by imajunryou** [comment]
That all sounds great.  I look forward to the future, and can work with this easily enough in its current state :smile:

**Comment by TheFloydman** [comment]
Alright, new release incoming. Thanks for your patience.
