### ISSUE TITLE
Libraries generate weirdly on flat maps

### ISSUE THREAD

**Issue by Sunconure11** [TheFloydman/More-Mystcraft#3]
![screenshot 2018-10-23 04 52 22](https://user-images.githubusercontent.com/5614902/47348443-81b34400-d67f-11e8-93f3-bae9b11cc524.png)

**Comment by TheFloydman** [comment]
Is this a flat overworld? They generate at a low Y level, and the Abandoned Studies are not placed lower than Y=64. Do you plan on playing in a flat overworld?

**Comment by TheFloydman** [comment]
I like giving more power to the player, so the minimum spawn height of Abandoned Studies will be a config option in the next release.
