### ISSUE TITLE
Startup Crash

### ISSUE THREAD

**Issue by 77wisher77** [TheFloydman/More-Mystcraft#4]
[Crash Report: crash-2018-12-29_07.04.36-client.txt](https://github.com/TheFloydman/More-Mystcraft/files/2715694/crash-2018-12-29_07.04.36-client.txt)

[Config: moremystcraft.txt](https://github.com/TheFloydman/More-Mystcraft/files/2715700/moremystcraft.txt)

Received this crash during startup. Happened after i updated from version `0.3.4` to version `0.4.2`.

Modpack is `Onion Sage Adventures` Version `B-0.6.0`
CurseForge Link: [OSA Curse](https://minecraft.curseforge.com/projects/onion-sage-adventures)
Gitlab Link: [OSA Gitlab](https://gitlab.com/Wisher/onion-sage-adventures)

I will update the issue as i get more information, and add better links, uploading version B-0.6.0 to curse and gitlab as i make this issue, so will link them directly later if you want that extra information/environment.

**Comment by 77wisher77** [comment]
[Gitlab: B-0.6.0](https://gitlab.com/Wisher/onion-sage-adventures/tree/Beta_0.6.0)

This is the modpack as it gets uploaded to curse to install via twitch, you can browse the files there if you need to see any details about the modpack if the error is not contained.

I can confirm the error dissapeared by disabling More `Mystcraft`, huge surprise right :P

**Comment by TheFloydman** [comment]
[moremystcraft-1.12.2-0.4.3.jar.zip](https://github.com/TheFloydman/More-Mystcraft/files/2716041/moremystcraft-1.12.2-0.4.3.jar.zip)
It looks like I need to update how I handle registration events. Try out this version and let me know if it still gives you an error. I don't know why it doesn't like the pack because it has been working fine on my end.

**Comment by 77wisher77** [comment]
Got a different crash with that version, assuming its a compile problem

<details>
<summary>
Crash Report:
</summary>
<p>

> [18:45:20] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
> [18:45:20] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
> [18:45:20] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
> [18:45:20] [main/INFO]: Forge Mod Loader version 14.23.5.2781 for Minecraft 1.12.2 loading
> [18:45:20] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at D:\Libraries\Documents\Curse\Minecraft\Install\runtime\jre-x64\1.8.0_51
> [18:45:21] [main/INFO]: Searching D:\Libraries\Documents\Curse\Minecraft\Instances\Onion Sage Adventures (2)\mods for mods
> [18:45:21] [main/INFO]: Searching D:\Libraries\Documents\Curse\Minecraft\Instances\Onion Sage Adventures (2)\mods\1.12.2 for mods
> [18:45:21] [main/WARN]: The coremod org.minimallycorrect.libloader.LibLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
> [18:45:21] [main/WARN]: The coremod LibLoader (org.minimallycorrect.libloader.LibLoader) is not signed!
> [18:45:22] [ForkJoinPool.commonPool-worker-4/INFO]: Downloading library org.javassist.javassist-3.22.0-CR1 from https://jcenter.bintray.com/org/javassist/javassist/3.22.0-CR1/javassist-3.22.0-CR1.jar. Expected hash: 1a955bad6b2755153f5abb8ee808b4ac002dc26f8d9c391ebba5d6743d5dd06efc2a1dcb70e5eac0396696f7583ea89f6b5d8c05f971f54f2d56a12a2bb50e82
> [18:45:23] [main/ERROR]: Unable to launch
> java.lang.RuntimeException: An error occurred trying to configure the Minecraft home at D:\Libraries\Documents\Curse\Minecraft\Instances\Onion Sage Adventures (2) for Forge Mod Loader
> 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:111) ~[forge-1.12.2-14.23.5.2781.jar:?]
> 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:81) ~[forge-1.12.2-14.23.5.2781.jar:?]
> 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:42) ~[forge-1.12.2-14.23.5.2781.jar:?]
> 	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:141) ~[forge-1.12.2-14.23.5.2781.jar:?]
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
> Caused by: java.lang.Error: java.lang.Error: Wrong hash for library org.javassist.javassist-3.22.0-CR1
> Expected 1a955bad6b2755153f5abb8ee808b4ac002dc26f8d9c391ebba5d6743d5dd06efc2a1dcb70e5eac0396696f7583ea89f6b5d8c05f971f54f2d56a12a2bb50e82, got cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51]
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51]
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51]
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51]
> 	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593) ~[?:1.8.0_51]
> 	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677) ~[?:1.8.0_51]
> 	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:735) ~[?:1.8.0_51]
> 	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160) ~[?:1.8.0_51]
> 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174) ~[?:1.8.0_51]
> 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[?:1.8.0_51]
> 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51]
> 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583) ~[?:1.8.0_51]
> 	at org.minimallycorrect.libloader.LibLoaderChained.init(LibLoaderChained.java:68) ~[%23%20LibLoader.jar:0.1-SNAPSHOT+Jenkins-b39.git-83f5a19f50db8bf0700b1e9abc953bae1c3ae517]
> 	at org.minimallycorrect.libloader.LibLoader.launch(LibLoader.java:66) ~[%23%20LibLoader.jar:0.1-SNAPSHOT+Jenkins-b39.git-83f5a19f50db8bf0700b1e9abc953bae1c3ae517]
> 	at org.minimallycorrect.libloader.LibLoader.init(LibLoader.java:55) ~[%23%20LibLoader.jar:0.1-SNAPSHOT+Jenkins-b39.git-83f5a19f50db8bf0700b1e9abc953bae1c3ae517]
> 	at org.minimallycorrect.libloader.LibLoader.<init>(LibLoader.java:25) ~[%23%20LibLoader.jar:0.1-SNAPSHOT+Jenkins-b39.git-83f5a19f50db8bf0700b1e9abc953bae1c3ae517]
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51]
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51]
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51]
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51]
> 	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51]
> 	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:594) ~[forge-1.12.2-14.23.5.2781.jar:?]
> 	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2781.jar:?]
> 	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2781.jar:?]
> 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2781.jar:?]
> 	... 5 more
> Caused by: java.lang.Error: Wrong hash for library org.javassist.javassist-3.22.0-CR1
> Expected 1a955bad6b2755153f5abb8ee808b4ac002dc26f8d9c391ebba5d6743d5dd06efc2a1dcb70e5eac0396696f7583ea89f6b5d8c05f971f54f2d56a12a2bb50e82, got cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e
> 	at org.minimallycorrect.libloader.LibLoaderChained$Library.validateHash(LibLoaderChained.java:232) ~[%23%20LibLoader.jar:0.1-SNAPSHOT+Jenkins-b39.git-83f5a19f50db8bf0700b1e9abc953bae1c3ae517]
> 	at org.minimallycorrect.libloader.LibLoaderChained$Library.save(LibLoaderChained.java:266) ~[%23%20LibLoader.jar:0.1-SNAPSHOT+Jenkins-b39.git-83f5a19f50db8bf0700b1e9abc953bae1c3ae517]
> 	at org.minimallycorrect.libloader.LibLoaderChained.lambda$init$1(LibLoaderChained.java:68) ~[%23%20LibLoader.jar:0.1-SNAPSHOT+Jenkins-b39.git-83f5a19f50db8bf0700b1e9abc953bae1c3ae517]
> 	at org.minimallycorrect.libloader.LibLoaderChained$$Lambda$18/1324843695.accept(Unknown Source) ~[?:?]
> 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_51]
> 	at java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(ConcurrentHashMap.java:3566) ~[?:1.8.0_51]
> 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51]
> 	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) ~[?:1.8.0_51]
> 	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) ~[?:1.8.0_51]
> 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51]
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51]
> 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51]
> 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51]
> [18:45:23] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
> [18:45:23] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
> [18:45:23] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
> [18:45:23] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
> [18:45:23] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:971)
> [18:45:23] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
> [18:45:23] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

</p>
</details>

**Comment by 77wisher77** [comment]
The original crash only appears to occur on the client.
I noticed that question in an email although i can't seem to see it here 💭

**Comment by TheFloydman** [comment]
Yeah, sorry about that. I realized that all client crash reports have "client" in the file name, so I deleted it.

**Comment by TheFloydman** [comment]
As for the new crash, it may have been a side effect of my crappy airport Wi-Fi connection. I have recompiled, and I was able to launch and start a world with no crash.

[moremystcraft-1.12.2-0.4.3.jar.zip](https://github.com/TheFloydman/More-Mystcraft/files/2717609/moremystcraft-1.12.2-0.4.3.jar.zip)

**Comment by TheFloydman** [comment]
If you can also confirm, I'll push out the new release ASAP.

**Comment by 77wisher77** [comment]
Sorry for the late response, didn't realise how much time had passed

The new version works perfectly as far as I can tell!
