### ISSUE TITLE
0.4.2 not pushed?

### ISSUE THREAD

**Issue by ishani** [TheFloydman/More-Mystcraft#5]
I wish to make a change to the dependency on LWJGL - but the current code on GitHub seems to be for 0.4.1

Can you push the latest up? The server I'm trying to fix is already using 0.4.2 and I'd rather not have the newer blocks removed.

**Comment by TheFloydman** [comment]
Whoops, thanks for the catch. I just pushed what I have. It is a bit past 0.4.2 because I had to implement a fix, but they are almost identical.

**Comment by ishani** [comment]
Thanks, got it working! 

FWIW, I had problems getting MM working on my headless Linux server - the use of the LWJGL vector/matrix code caused problems as it refused to load and use LWJGL, despite it being installed. While there's probably a better fix, I just cloned that code into MM directly (the sun tilt calculations, specifically)

**Comment by TheFloydman** [comment]
Thanks for the heads up. I believe Minecraft has it's own way of doing vectors, so I may look at using that in the future.

**Comment by TheFloydman** [comment]
FYI in the [most recent version](https://minecraft.curseforge.com/projects/more-mystcraft/files/2658204), I have started including the LWJGL classes in More Mystcraft itself, so there is not a need to upload the library to the server.
