### ISSUE TITLE
[1.12.2] Crash with new version on start up

### ISSUE THREAD

**Issue by NickelHub** [TheFloydman/More-Mystcraft#6]
[crash-2019-01-01_23.47.42-client.txt](https://github.com/TheFloydman/More-Mystcraft/files/2719699/crash-2019-01-01_23.47.42-client.txt)

**Comment by TheFloydman** [comment]
_More Mystcraft_ requires _Mystcraft_ to work. It appears you do not have _Mystcraft_ in your modpack. Add _Mystcraft_ to your modpack, and then see how things go.

**Comment by NickelHub** [comment]
My fault.
