### ISSUE TITLE
Blockstate Errors?

### ISSUE THREAD

**Issue by O13SC3N3** [TheFloydman/More-Mystcraft#7]
Doesn't seem to be causing any problems so far, but still early on. This was on startup.

https://pastebin.com/85GiCriD

**Comment by TheFloydman** [comment]
If you're talking about the locked books and and locked lectern errors, they are a side effect of extending Mystcraft's bookstand and lectern classes. It doesn't show in-game because they have custom renderers. But I'll see if I can make the errors go away.

**Comment by TheFloydman** [comment]
Figured out what was going on here, and these errors will disappear in the next release.
